// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - .open-next/worker.js is generated by opennextjs-cloudflare build.
import { default as handler } from "./.open-next/worker.js";

type CronEvent = {
  cron: string;
};

type ExecutionContextLike = {
  waitUntil(promise: Promise<unknown>): void;
};

type CloudflareEnv = {
  CRON_SECRET?: string;
};

const CRON_ROUTES: Record<string, string> = {
  "0 0 * * 1": "/api/cron/sync-items",
  "0 2 * * 1": "/api/cron/sync-recipes",
  "0 4 * * *": "/api/cron/sync-prices",
};

async function runCronRoute(event: CronEvent, env: CloudflareEnv, ctx: ExecutionContextLike) {
  const path = CRON_ROUTES[event.cron];
  if (!path) {
    console.error(`[cloudflare-cron] No route configured for cron "${event.cron}"`);
    return;
  }

  const response = await handler.fetch(
    new Request(`https://immo-web-suite.internal${path}`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.CRON_SECRET ?? ""}`,
        "x-cloudflare-cron": event.cron,
      },
    }),
    env,
    ctx
  );

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`[cloudflare-cron] ${path} failed with ${response.status}: ${body}`);
  }
}

const cloudflareWorker = {
  fetch: handler.fetch,

  scheduled(event: CronEvent, env: CloudflareEnv, ctx: ExecutionContextLike) {
    ctx.waitUntil(runCronRoute(event, env, ctx));
  },
};

export default cloudflareWorker;
